# mapping.py
mapping_malware_object = {
    'appliance_id': 'appliance-id',
    'product': 'product',
    'version': 'version',
    'appliance': 'appliance',
    'msg': 'msg',
    'alert_id': 'alert.id',
    'alert_name': 'alert.name',
    'alert_uuid': 'alert.uuid',
    'alert_ack': 'alert.ack',
    'alert_sc_version': 'alert.sc-version',
    'alert_severity': 'alert.severity',
    'alert_explanation_analysis': 'alert.explanation.analysis',
    'alert_explanation_protocol': 'alert.explanation.protocol',
    'malware': {
        'sid': 'alert.explanation.malware-detected.malware.sid',
        'name': 'alert.explanation.malware-detected.malware.name',
        # ... other malware attributes ...
    },
    'cnc_services': {
        'port': 'alert.explanation.cnc-services.cnc-service.port',
        'protocol': 'alert.explanation.cnc-services.cnc-service.protocol',
        # ... other cnc-services attributes ...
    },
    'src_vlan': 'alert.src.vlan',
    'src_ip': 'alert.src.ip',
    'src_mac': 'alert.src.mac',
    'src_port': 'alert.src.port',
    'dst_ip': 'alert.dst.ip',
    'dst_mac': 'alert.dst.mac',
    'dst_port': 'alert.dst.port',
    'alert_action': 'alert.action',
    'alert_url': 'alert.alert-url',
    'alert_occurred': 'alert.occurred'
}

mapping_web_infection = {
    'appliance_id': 'appliance-id',
    'product': 'product',
    'version': 'version',
    'appliance': 'appliance',
    'msg': 'msg',
    'alert_id': 'alert.id',
    'alert_name': 'alert.name',
    'alert_uuid': 'alert.uuid',
    'alert_ack': 'alert.ack',
    'alert_sc_version': 'alert.sc-version',
    'alert_severity': 'alert.severity',
    'alert_explanation_analysis': 'alert.explanation.analysis',
    'alert_explanation_protocol': 'alert.explanation.protocol',
    'alert_explanation_urls': 'alert.explanation.urls',
    'malware': 'alert.explanation.malware-detected.malware',
    'cnc_services': 'alert.explanation.cnc-services.cnc-service',
    'target_os': 'alert.explanation.target-os',
    'target_application': 'alert.explanation.target-application',
    'service': 'alert.explanation.service',
    'src_vlan': 'alert.src.vlan',
    'src_ip': 'alert.src.ip',
    'src_mac': 'alert.src.mac',
    'src_port': 'alert.src.port',
    'src_host': 'alert.src.host',
    'dst_ip': 'alert.dst.ip',
    'dst_mac': 'alert.dst.mac',
    'dst_port': 'alert.dst.port',
    'alert_action': 'alert.action',
    'alert_url': 'alert.alert-url',
    'alert_occurred': 'alert.occurred'
}